
import type { Metadata } from "next";
import { connection } from "next/server";
import { Noto_Serif_Bengali } from "next/font/google";
import { Suspense } from "react";
import "./globals.css";
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";
import { Icategories, IcategoryProducts } from "@/type";
import { fetchBazardorData } from "@/lib/bazardor-api";


const geistSans = Noto_Serif_Bengali({
  
  subsets: ["latin","bengali"],
});

const getAllProducts = async()=>{
    return fetchBazardorData<IcategoryProducts[]>('/api/bazardor/products')
}


const getCategories =async()=>{
return fetchBazardorData<Icategories[]>('/api/bazardor/categories')
}

async function NavbarData() {
  await connection()

  const [catagories, allProducts] = await Promise.all([
    getCategories(),
    getAllProducts(),
  ])

  return <Navbar catagories={catagories} allProducts={allProducts} />
}

async function FooterData() {
  await connection()
  return <Footer />
}


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
    data-theme="light"
      lang="en"
      className={`${geistSans.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#F3FBF4]">
        <Suspense fallback={<div className="h-28" aria-hidden="true" />}>
          <NavbarData />
        </Suspense>
       <main className="flex-1">
         {children}
       </main>
       <Suspense fallback={<div className="h-40" aria-hidden="true" />}>
         <FooterData />
       </Suspense>
       </body>
    </html>
  );
}
