import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";

const geistSans = Noto_Serif_Bengali({
  
  subsets: ["latin","bengali"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
    data-theme="light"
      lang="en"
      className={`${geistSans.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#F3FBF4]">
        <Navbar></Navbar>
       <main>
         {children}
       </main>
        </body>
    </html>
  );
}
